services:

  frontend:
    image: node:22-bookworm
    container_name: tarawit-frontend-dev

    working_dir: /app

    volumes:
      - ./Tarawit-frontend:/app
      - frontend_node_modules:/app/node_modules

    ports:
      - "5173:5173"

    environment:
      CHOKIDAR_USEPOLLING: "true"

    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

    depends_on:
      - server

    networks:
      - tarawit-network


  server:
    build:
      context: ./server

    container_name: tarawit-server-dev

    working_dir: /app

    volumes:
      - ./server:/app
      - ./storage/attachments:/app/storage/attachments
      - ./storage/avatars:/app/storage/avatars

    environment:
      DB_HOST: db
      DB_PORT: "5432"
      POSTGRES_USER: yeawyow
      POSTGRES_PASSWORD: 481725209mM
      POSTGRES_DB: tarawitDB
      DB_SSLMODE: disable

    ports:
      - "8000:8000"

    command: air

    depends_on:
      - db

    networks:
      - tarawit-network


  db:
    image: postgres:15

    container_name: postgresDB

    environment:
      POSTGRES_USER: yeawyow
      POSTGRES_PASSWORD: 481725209mM
      POSTGRES_DB: tarawitDB

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - tarawit-network


volumes:
  postgres_data:
  frontend_node_modules:


networks:
  tarawit-network:
