services:
  db:
    image: postgres:15
    container_name: postgresDB
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - gateway_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api-service:
    build: 
      context: ./tarawit-api
      dockerfile: ${DOCKERFILE_PATH}
    container_name: tarawit_api 
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      APP_ENV: ${APP_ENV}
      JWT_SECRET: ${JWT_SECRET}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    ports:
      - "8080:8080"
    volumes:
      - ./tarawit-api:/app
      # - /app/node_modules
    networks:
      - gateway_net

networks:
  gateway_net:
    driver: bridge

volumes:
  db_data: