ALTER TABLE attendance_settings
    ADD COLUMN IF NOT EXISTS check_in_open TIME NOT NULL DEFAULT '05:00:00',
    ADD COLUMN IF NOT EXISTS check_in_close TIME NOT NULL DEFAULT '12:00:00',
    ADD COLUMN IF NOT EXISTS check_out_open TIME NOT NULL DEFAULT '12:00:00',
    ADD COLUMN IF NOT EXISTS check_out_close TIME NOT NULL DEFAULT '23:00:00';
