services:

  nginx:
    image: nginx:alpine
    container_name: tarawit-nginx
    restart: always

    ports:
      - "80:80"

    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

    depends_on:
      - api

    networks:
      - tarawit-network


  api:
    build:
      context: ./server

    container_name: tarawit-api

    restart: always

    environment:
      DB_HOST: db
      DB_PORT: "5432"
      POSTGRES_USER: yeawyow
      POSTGRES_PASSWORD: 481725209mM
      POSTGRES_DB: tarawitDB

    expose:
      - "8000"

    depends_on:
      - db

    networks:
      - tarawit-network


  db:
    image: postgres:15

    container_name: tarawit-postgres

    restart: always

    environment:
      POSTGRES_USER: yeawyow
      POSTGRES_PASSWORD: 481725209mM
      POSTGRES_DB: tarawitDB

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - tarawit-network


volumes:
  postgres_data:


networks:
  tarawit-network:
    driver: bridge