# upstream api-serivce {
#     server api-service:8081;  # ใช้ service name แทน IP
# }
server {
    listen 8081;
    server_name localhost;
    client_max_body_size 0;

    # กำหนด base path เป็น /drugnarco (เปลี่ยนได้ง่าย)
   # set $base_path /drugnarco;

    # ===============================
    # API Gateway
    # ===============================
    location ^~ /api-service/ {
        proxy_pass http://api-service/;
         proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    }
    
}